// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type listenListenEventT struct {
	Uid      uint32
	Pid      uint32
	Ppid     uint32
	Retval   int32
	Ret      int32
	Pwd      [128]int8
	Addr     uint32
	Port     uint16
	Socktype uint16
	Backlog  uint32
}

// loadListen returns the embedded CollectionSpec for listen.
func loadListen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ListenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load listen: %w", err)
	}

	return spec, err
}

// loadListenObjects loads listen and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*listenObjects
//	*listenPrograms
//	*listenMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadListenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadListen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// listenSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type listenSpecs struct {
	listenProgramSpecs
	listenMapSpecs
}

// listenSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type listenProgramSpecs struct {
	KprobeInetListen    *ebpf.ProgramSpec `ebpf:"kprobe_inet_listen"`
	KretprobeInetListen *ebpf.ProgramSpec `ebpf:"kretprobe_inet_listen"`
}

// listenMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type listenMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// listenObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadListenObjects or ebpf.CollectionSpec.LoadAndAssign.
type listenObjects struct {
	listenPrograms
	listenMaps
}

func (o *listenObjects) Close() error {
	return _ListenClose(
		&o.listenPrograms,
		&o.listenMaps,
	)
}

// listenMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadListenObjects or ebpf.CollectionSpec.LoadAndAssign.
type listenMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *listenMaps) Close() error {
	return _ListenClose(
		m.Events,
	)
}

// listenPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadListenObjects or ebpf.CollectionSpec.LoadAndAssign.
type listenPrograms struct {
	KprobeInetListen    *ebpf.Program `ebpf:"kprobe_inet_listen"`
	KretprobeInetListen *ebpf.Program `ebpf:"kretprobe_inet_listen"`
}

func (p *listenPrograms) Close() error {
	return _ListenClose(
		p.KprobeInetListen,
		p.KretprobeInetListen,
	)
}

func _ListenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed listen_bpfel.o
var _ListenBytes []byte
