// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type openOpenEventT struct {
	Uid      uint32
	Pid      uint32
	Ppid     uint32
	Retval   int32
	Ret      int32
	Pwd      [128]int8
	Dfd      int16
	Filename [80]int8
	_        [2]byte
	Flags    int32
}

// loadOpen returns the embedded CollectionSpec for open.
func loadOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load open: %w", err)
	}

	return spec, err
}

// loadOpenObjects loads open and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openObjects
//	*openPrograms
//	*openMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openSpecs struct {
	openProgramSpecs
	openMapSpecs
}

// openSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openProgramSpecs struct {
	TpEnterOpenat *ebpf.ProgramSpec `ebpf:"tp_enter_openat"`
	TpExitOpenat  *ebpf.ProgramSpec `ebpf:"tp_exit_openat"`
}

// openMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// openObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type openObjects struct {
	openPrograms
	openMaps
}

func (o *openObjects) Close() error {
	return _OpenClose(
		&o.openPrograms,
		&o.openMaps,
	)
}

// openMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type openMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *openMaps) Close() error {
	return _OpenClose(
		m.Events,
	)
}

// openPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type openPrograms struct {
	TpEnterOpenat *ebpf.Program `ebpf:"tp_enter_openat"`
	TpExitOpenat  *ebpf.Program `ebpf:"tp_exit_openat"`
}

func (p *openPrograms) Close() error {
	return _OpenClose(
		p.TpEnterOpenat,
		p.TpExitOpenat,
	)
}

func _OpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed open_bpfeb.o
var _OpenBytes []byte
