// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type readlineReadlineEventT struct {
	Uid    uint32
	Pid    uint32
	Ppid   uint32
	Retval int32
	Ret    int32
	Pwd    [128]int8
	Str    [80]int8
}

// loadReadline returns the embedded CollectionSpec for readline.
func loadReadline() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ReadlineBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load readline: %w", err)
	}

	return spec, err
}

// loadReadlineObjects loads readline and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*readlineObjects
//	*readlinePrograms
//	*readlineMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadReadlineObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadReadline()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// readlineSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readlineSpecs struct {
	readlineProgramSpecs
	readlineMapSpecs
}

// readlineSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readlineProgramSpecs struct {
	UretprobeBashReadline *ebpf.ProgramSpec `ebpf:"uretprobe_bash_readline"`
}

// readlineMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readlineMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// readlineObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadReadlineObjects or ebpf.CollectionSpec.LoadAndAssign.
type readlineObjects struct {
	readlinePrograms
	readlineMaps
}

func (o *readlineObjects) Close() error {
	return _ReadlineClose(
		&o.readlinePrograms,
		&o.readlineMaps,
	)
}

// readlineMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadReadlineObjects or ebpf.CollectionSpec.LoadAndAssign.
type readlineMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *readlineMaps) Close() error {
	return _ReadlineClose(
		m.Events,
	)
}

// readlinePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadReadlineObjects or ebpf.CollectionSpec.LoadAndAssign.
type readlinePrograms struct {
	UretprobeBashReadline *ebpf.Program `ebpf:"uretprobe_bash_readline"`
}

func (p *readlinePrograms) Close() error {
	return _ReadlineClose(
		p.UretprobeBashReadline,
	)
}

func _ReadlineClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed readline_bpfeb.o
var _ReadlineBytes []byte
